### PR TITLE
Add a shortcut for the goLive button from the editor

### PR DESCRIPTION
**Pull request by etienneCharignon**
It uses ctrl-alt-g on windows or linux (if I understand)
and cmd-alt-g on mac.

I've been testing on Mac and I would be glad if someone could validate on windows and linux.

### CODE REVIEW

**Comment by jonathanperret** [comment]
Pretty neat that ACE can handle shortcuts!

JsBin and JSfiddle both use `cmd/ctrl`+`enter` to run code, could this work? A bit easier to discover/remember than `ctrl+alt+g`…

**Comment by juliendorra** [comment]
I second meta+enter, it seems to not conflict with a browser shortcut. 
Nice if it is coherent with other web code scratch pads as user can use their learned habits.
(Not sure about ctrl - alt - g? It should be safe too)

**Comment by etienneCharignon** [comment]
#91

**Comment by jonathanperret** [comment]
Great!

**Pull request merged**
