### PR TITLE
Newest object is on top

### PR DESCRIPTION
**Pull request by juliendorra**
As per issue #79, adopt a "Photoshop layers"-like approach to the list:
the newest object –which is also rendered in the top-most canvas– is listed on top.

### CODE REVIEW

**Comment by juliendorra** [comment]
hmm, another test that seems to not test what it says it test:

>  - A listed code object can be deleted (13.225s)
>    Expected element <#objects li:last-of-type a:first-of-type> text to equal: "jul"  - expected "equal 'jul'" but got: "jim"
>        at Object.A listed code object can be deleted (/home/travis/build/jonathanperret/paysage/e2etests/tests/test.js:48:15)

Objects can indeed still be deleted, but the inversion of the list must have confused the test, that rely on a (unstable?) selector.

**Comment by jonathanperret** [comment]
The test is not so much instable as depending on the listing order, which is precisely what you are changing. I agree that it’s not what the test purports to check, but it’s an unfortunate fact that end-to-end tests tend to depend on more than one behavior.

Can you please fix the test? Reminder: `npm test` runs all tests.

**Comment by juliendorra** [comment]
> Can you please fix the test? 
Yes! I'll try to find a way to make it not depending on list order, if there's a way. Ideas?

> Reminder: npm test runs all tests.

Yes, trying to do that locally for a few days now, but there's always something broken :-( Now it's PhantomJS
```
not ok 1 PhantomJS 2.1 - Global error: ReferenceError: Can't find variable: describe at http://localhost:7357/spec/public/programmer_spec.js, line 3
    ---
        Log: |
            { type: 'error',
              text: 'ReferenceError: Can\'t find variable: describe at http://localhost:7357/spec/public/programmer_spec.js, line 3\n' }
    ...
```

**Comment by jonathanperret** [comment]
That’s weird… unless your dependencies are out of date, then anything can happen!

Try this:
```
$ rm -rf node_modules bower_components
$ npm install
```

There may also be something fishy with your Node installation, as you experienced some unexplained behavior around `bower` earlier. Which version are you running?

**Comment by juliendorra** [comment]
Thanks @etienneCharignon :-) 
Merging now.

**Comment by jonathanperret** [comment]
Did you manage to get the tests running locally?

**Comment by juliendorra** [comment]
not yet working on it :-(

**Pull request merged**
