### PR TITLE
Upgrade to latest node version

### PR DESCRIPTION
**Pull request by etienneCharignon**

### CODE REVIEW

**Comment by jonathanperret** [comment]
Thanks! My notes:

* If you wish to upgrade `node`, please update `.travis.yml` as well so that the requested version is tested.
* `node` 9 includes `npm` 5.6, which always creates a `package-lock.json` when running  `npm install`. This file should be committed. Currently, if I take your branch and run `npm install` git complains about an untracked file (`package-lock.json`) and a cosmetic change in `package.json`: running `npm install` should not create Git-visible changes.
* I will want to be sure that this runs correctly on Heroku before merging. Can you check this?

**Comment by etienneCharignon** [comment]
I did your recommandations but dont merge this PR, yet. I've been noticed by npm of a few deprecated package : 
```
npm WARN deprecated formatio@1.2.0: This package is unmaintained. Use @sinonjs/formatio instead
npm WARN deprecated wrench@1.3.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
```

I will be trying to upgrade also these dependencies, one by one to ease regression tests.

**Comment by etienneCharignon** [comment]
- I managed to solve the deprecated dependencies formatio and wrench. 
- graceful-fs is from cli-real-favicon@0.0.6 that do not have more recent version.
- socks is a dependency of nightwatch@0.9.21 that should be upgraded but it's harder work that could be done in a dedicated PR.

Could you merge that PR as is?

**Comment by jonathanperret** [comment]
I bumped Node to 10.1, as 9.11 was already not the latest version when you opened this PR 😉— and more seriously, 9.x is not an LTS branch and will become unsupported a month from now.

**Comment by etienneCharignon** [comment]
👻

**Pull request merged**
