### PR TITLE
More namespacing and IIFE

### PR DESCRIPTION
**Pull request by juliendorra**
IIFE for less globals.
Named callbacks for better expressing intentions.

### CODE REVIEW

**Comment by juliendorra** [comment]
Hi, @etienneCharignon @jonathanperret, need your help there: Travis says this test fail:

Workshop works too  Failed [equal]: (There should be two open windows.)  - expected "2" but got: "1"     

in paysage/e2etests/tests/test.js:80:21

I checked manually, and the /workshop/creature page works as intended, the playground open. No bugs that I can see here.

Not sure what is happening, but i'm under the impression that the test is not testing what it thinks it tests (that a playground windows open when we click the [open in new window] button, is I'm not mistaken).

**Comment by jonathanperret** [comment]
I just rebased your branch since I the fix for the unstable test is now in master.

**Comment by jonathanperret** [comment]
Working on the conflicts I created in #83 right now.

**Comment by jonathanperret** [comment]
That's a good cleanup, thanks!

**Comment by jonathanperret** [comment]
You may note I reverted the naming of callbacks, which I find distasteful. I thought we had had that conversation already but it may have been with someone else…  I'm open to rehashing the subject but in person please 😄

**Pull request merged**
