### PR TITLE
Issue #31: Namespacing the rest of the functions and variables

### PR DESCRIPTION
**Pull request by juliendorra**
Hopefully there's no more globals and we can close issue #31

### CODE REVIEW

**Comment by jonathanperret** [comment]
Thanks. Aren’t there a couple more globals in the renderer?

**Comment by jonathanperret** [comment]
Oh, and for functions / variables that are local to a module, there’s a better way than adding them all to the global `Paysage` object : wrap all the code in an immediately-executed function expression (IIFE). See https://github.com/jonathanperret/paysage/blob/master/public/programmerjs/receptiontransmission.js where it has been done already.

**Comment by juliendorra** [comment]
OK for the locals, I'll try a pass to IIFE them, can you point me to one example?

I also checked `let` support and it's still a bit too recent to be used instead–for example Safari 9 in El Capitan OS X 10.11 doesn't support them (but Safari 10 in 10.12 is ok) . As we have no precise stance on support, let's not be even more Chrome-oriented here.

As for receptiontransmission.js, there's 2 thing that would make it clearer for me in term of scoping intentions:
put Paysage.requestCode out the IIFE, as it is meant to be also called from elsewhere, and it's now lost in between local `var`s
```
Paysage.requestCode = function (codeObjectId) {
    var data = {
      codeObjectId: codeObjectId
    };
    io.emit('request code', data);
  };

```
and use a `var` declaration for deleteCode (not really sure about where hoisting will move the scope here. But a var would be clear that the intended scope is the enclosing function) as such:

```
var deleteCode = function (codeObjectId) {
    var data = {
      codeObjectId: codeObjectId
    };
    io.emit('code delete', data);
  }
```
I have a patch coming

**Comment by jonathanperret** [comment]
Hi!

I have a couple issues with the idea of moving published functions like `requestCode` outside of the IIFE:
* first, it can’t be done in general : published functions tend to need access to variables and functions private to the module. In this case it is the `io` variable – it only works outside of the IIFE because earlier we (abusively) replaced the global `io` variable provided by the socket.io client lib with our socket instance ;
* then, this “whole module in IIFE” pattern is very well known and recognized by JS programmers, and helps smooth over the differences from a CommonJS environment where basically every module is automatically wrapped in an invisible function. Deviating from it would add more confusion than utility, I fear.

I’m afraid I’m not a fan of using `var` instead of `function` either. Function declarations are hoisted and scoped just like variables, so I don’t see what à verbose and mutable replacement buys us?

🤗 anyway!

**Comment by juliendorra** [comment]
You're right, moving requestCode didn't even worked in my tests. That should be goof that in the new branch #82

As for `var` versus `function`, I find `var` more readable/agreedable for… whatever reason!!! Well, it must be because I'm a verbose guy ;-)

(and of of course I can't argue if you find function more readable!). 

I believe functions are mutable in all cases? As in: I can redefine a function created with both forms?

In any case, let's revert back to `function` in #82 as a way to clearly express: this is not a function you should redefine.

**Comment by juliendorra** [comment]
(now that I think of it, it must be the beauty of having a consistent way to do things that make me prefer `var` over `function`. Whatever.)

**Pull request merged**
