### PR TITLE
Improve code examples

### PR DESCRIPTION
**Pull request by etienneCharignon**
The new error detection mecanisme seams to have revealed error in examples.

- usermasstmp was undefined in creature.pde
- change serpent implementation so that "changeTaCouleur" could be used in the setup

### CODE REVIEW

**Comment by jonathanperret** [comment]
❤️ this. Keep going!😘

**Comment by etienneCharignon** [comment]
I'd be pleased to keep going on this improvement but could we merge this rapidly to fix the fact that, today, the creature example is not working ?

**Comment by jonathanperret** [comment]
It doesn’t? 😮 
I wasn’t expecting the new error reporting to impact behavior but thinking about it, there is something new: we stop execution at the first error. I guess that’s what happens here.

**Comment by jonathanperret** [comment]
Looking into it a bit more, I realized the exact problem was that when I worked on the error-handling code, I changed the way the compiled code was evaluated. Long story short, it is now evaluated in strict mode whereas that wasn't the case before.
I know how to go back to non-strict mode (keeping the error-handling features working, of course) but if everything works in strict mode I'd rather leave it as-is.

**Pull request merged**
