### PR TITLE
Fix the serpent white glitch when it turns

### PR DESCRIPTION
**Pull request by etienneCharignon**
set the fill of the vertex to transparent to avoid the white glitch. Also change the color to give an example of how to do it

### CODE REVIEW

**Comment by juliendorra** [comment]
We could use this branch to make a better suited Serpent example: easier to read, easier to hack for fun, easier to extend.

**Comment by etienneCharignon** [comment]
I like to keep the fill function close to the curveVertex() to give a clue to the developer about it's role in this code.

What do you think ?

**Comment by jonathanperret** [comment]
I love the idea of improving the examples, they do need it!

This PR is already a nice improvement as it stands, but I agree that there's a lot more code that can be removed from this example, which started out as a customizable creature and retains vestiges of this complicated past. I'm not even sure it needs a class, for a start.

The language (French vs English) is a tricky question. Will we need a localization system at some point?

@etienneCharignon are you willing to go further in the simplification of this example in this PR? If not, I'll merge what we have now and we can come back to it later, just let me know.

**Comment by etienneCharignon** [comment]
I've done this new simplification (I love coding in the morning when kids sleep). I won't do more.

**Comment by jonathanperret** [comment]
Thanks for the improvements! 💟

**Pull request merged**
